version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www/html  # Mapea tu directorio local al contenedor
    networks:
      - app-network
    ports:
      - "8000:8000"  # Exponer el puerto del backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/app  # No sobrescribir la carpeta build
    networks:
      - app-network
    ports:
      - "5173:5173"  # Exponer el puerto del frontend

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
