version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www/html # Mapea tu directorio local al contenedor
    networks:
      - app-network
    ports:
      - "8000:8000" # Exponer el puerto del backend
    depends_on:
      - db # Asegúrate de que la base de datos esté disponible antes de iniciar el backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/app # Mapea tu directorio local al contenedor
    networks:
      - app-network
    ports:
      - "5173:5173" # Exponer el puerto del frontend

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql # Almacena los datos de la base de datos
      - ./db/init:/docker-entrypoint-initdb.d # Archivos SQL de inicialización
    networks:
      - app-network
    ports:
      - "3306:3306" # Exponer el puerto de MySQL para desarrollo local

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
